[package]
name = "mkprompt"
version = "0.1.0"
authors = ["Rogach <platon7pronko@gmail.com>"]
edition = "2018"

# [profile.release]
# lto = true

[dependencies]

[dev-dependencies]
criterion = "0.2.7"

[[bench]]
name = "main"
harness = false